Port RSBAC from 5.4 git commit 94f6252b9cf5e460992e2e9a5fb475d6fce42fe1     arch/*/include/uapi/asm/unistd.h: do not leak CONFIG_RSBAC to user space
Squashed commit of the following:

commit 60129af82e19885378754cb084833a17cf4b23d5
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jul 23 12:20:48 2020 +0200

    arch/*/include/uapi/asm/unistd.h: do not leak CONFIG_RSBAC to user space

commit e9fe526162d9f187954f5b5941aef74a36534dd7
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jul 23 09:28:23 2020 +0200

    arch/alpha/include/uapi/asm/unistd.h: do not leak CONFIG_RSBAC to user space

commit 85a307ca1ee8115a32ae5a506a51242965dd3130
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jul 22 07:57:14 2020 +0200

    gen_lists: also mark lists dirty, if ttl has changed.

commit d30c260aab4e6f647925cdecb6c89bd13cc58e05
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Jul 14 17:32:51 2020 +0200

    gen_lists: only copy list item data and mark list dirty, if data has changed.

commit 159bf9738b0f7b50ae8b06aede241d628edbcd2b
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jun 25 10:44:54 2020 +0200

    Remove #ifdef CONFIG_RSBAC from include/uapi/linux/sched.h
    This avoids the following error at make headers_install:
    error: include/uapi/linux/sched.h: leak CONFIG_RSBAC to user-space

commit 6583bd759f03d7533411e0cbf61928ea83ebcd63
Author: Amon Ott <ao@rsbac.org>
Date:   Fri May 8 13:46:03 2020 +0200

    Silence noisy debug printk in rsbac_get_all_res_limits()

commit 97a1a9db372c60aa550defbb92310b59fbcfae21
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Apr 30 11:20:24 2020 +0200

    Revert f0483ea986bf648937103c710c5f042146afd2a5 for include/rsbac/gen_lists.h
    This fix was wrong and lead to NULL pointer dereference.

commit 4827de20206482995d6108027ea584f16d7bafea
Author: Amon Ott <ao@rsbac.org>
Date:   Fri Apr 24 09:49:11 2020 +0200

    Fix some compile warnings.

commit 3c4ff6f72bbaf39723d9bf5aa9e1c7fb452d2b5d
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Apr 22 10:54:28 2020 +0200

    Remove decision modules PAX and DAZ. Bump version to 1.5.5 to reflect that.

commit 82fdee01d9b4b94aa63a94bc6bcfbb620ac12f0d
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Mar 31 12:47:17 2020 +0200

    Deprecate decision modules PAX and DAZ.
    Both PaX and Dazuko support have been obsolete for a long time.

commit d4d6bb03047161172ab55baff10d50c4b551ed83
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Mar 31 12:44:06 2020 +0200

    Small cleanup in secure delete.

commit f0e5bccc5d3ca2a1d24b6408794e88de9ccd77c8
Author: Amon Ott <ao@rsbac.org>
Date:   Fri Mar 27 15:31:31 2020 +0100

    Use major, minor for devices internally and serialize all mounts to avoid races.
    Mark auto mounted devices and replace with real when rsbac_mount() is called.

commit 8837899bf6ef072ec0f01bd9eea7890bdd5b083a
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Mar 26 15:24:58 2020 +0100

    Use new rsbac_dev_t (__u32) instead of old style kdev_t for devices.

commit f64010acff636413728a001550be66e5bd00460b
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Mar 26 12:50:11 2020 +0100

    rc_main: always show error in error message after failed rsbac_[gs]et_attr().

commit c88da89423a3da778aa883d171551a092845af5b
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Mar 2 09:36:46 2020 +0100

    Add SCD target type perf, extend sys_perf_event_open() with ADF request.

commit 609be8b0ab6561863d7946b48863230a984717d1
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Feb 12 09:20:18 2020 +0100

    Compile fix in ipc/msg.c for new structures in 5.4.19.

commit dfbadad85067f32b571ab7cbeb75654b67537dfc
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jan 30 16:00:20 2020 +0100

    rc_main: add missing #ifdef CONFIG_RSBAC_DEBUG
    Thanks to Jan Mazur for telling.

commit c6db4477bee9dd6aac2fee99895df9e8e07b0eb0
Author: Amon Ott <ao@rsbac.org>
Date:   Fri Jan 17 10:20:48 2020 +0100

    aci_data_structures: if device not found, try to auto mount, if possible.
    Auto mounting is restricted to devices which may not have attributes stored,
    because the vfsmount_p is not available at that time. Inheritance from
    parent mounts cannot work either for all auto mounted devices.

commit cd1f2062989758c1222bf674a58ff9a239298e00
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jan 15 15:11:13 2020 +0100

    Also provide parent mount to rsbac_mount(), force rsbac_mount(parent), if missing.

commit 99ab40a360e04233b8d976d00cfb63d1b42e9b73
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jan 15 09:06:32 2020 +0100

    aci_data_structures: list more FS types as not writable.

commit 2896c1197a1203b3bb6a857d21ee8dfa93047e7b
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jan 15 08:39:02 2020 +0100

    rsbac_umount(): before init, only remove one saved mount per call.
    The same vfsmount can be mounted more than once and some, but not all of these
    mounts might be umounted, leaving RSBAC without device entry if we remove all
    entries in the list.

commit c482e74ec9fd75c0c6ae233b4c3f3fad9ca9fc67
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Dec 23 11:31:12 2019 +0100

    Work around an invalid kernel pointer in filp_close().

commit c5ef140511fbcc65a8b56b253efbb907b402758b
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Dec 17 09:51:53 2019 +0100

    New kernel config for number of days after which expired passwords turn unset.
    If a password has been expired for this number of days, it is treated as unset.
    This effectively avoids password warnings when logging in with other
    authentication methods. The value set here can be overridden with kernel
    parameter rsbac_um_old_pw_unset_days=N or through proc file debug.
    Set to -1 (default) to use 2 * user's inactive days value or to 0 to disable.

commit 4aaf41756aca2909afa6d799192c32eb4dec8725
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Dec 16 08:42:51 2019 +0100

    Log errors returned by AUTH helper functions.

commit 2efe224abe6bff1cd8aa0ea07c68b61ebaaada35
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 11 12:28:06 2019 +0100

    Follow old inheritance rules when converting old RES lists to new lists of lists.

commit fa58f6c791e733c164cbf0426c4bcdea3566eb83
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 11 11:25:42 2019 +0100

    With debug_adf_res, also show process owner.

commit 43d2ea369fb6cd614debdfda4aff5e6d9c1f3351
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 11 09:30:57 2019 +0100

    Limit RES limit values to RLIM_INFINITY, if it is not 0.

commit a3e40200e9c00b70011db4daf91d0dc4e2c9c4c8
Author: Amon Ott <ao@rsbac.org>
Date:   Fri Dec 6 13:47:41 2019 +0100

    Change RES res_min and res_max storage to lists of lists
    Try to convert old lists, if new lists are empty.
    Mostly rewrite how res_min and res_max get accessed while keeping the old
    interfaces for backwards compatibility.
    Add new RSBAC syscalls to get and set RES limits individually and with ttls.
    This change makes inheritance from RES default user to normal users work
    as expected: inherit individual values, not everything together, and use
    own settings where set.

commit 8dc63d57eb2650c7fc20d4ceca7980db8fb5f090
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Dec 5 13:51:58 2019 +0100

    Require minimum password hash algo hash size of 20 bytes (160 bits).

commit 71d388e4d7d177498a4bf25540872898916c14f4
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 4 12:58:06 2019 +0100

    Convert one-time password list to new password format and provide new hash syscalls.

commit 3dddebb838e05769bae0e8836a17f3f89700f8bf
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 4 10:24:45 2019 +0100

    Convert password history list to new password format.

commit f92c45cfe64c8572e0d6ac8c7113cb198853c62d
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Dec 4 08:30:18 2019 +0100

    Move auth_may_set_cap check back from auth_main.c to syscalls.c.
    If a process has auth_may_set_cap, ADF should not be called at all.

commit 374d8f2459157e04e91c4a516158cdd4d4ca250e
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Dec 3 10:51:26 2019 +0100

    Also allow to add AUTH process caps, if all modules grant MODIFY_ATTRIBUTE
    All modules check MODIFY_ATTRIBUTE on the new A_auth_add_p_cap and
    A_auth_remove_p_cap pseudo attributes the same way as A_auth_add/remove_f_cap.
    If the calling process has auth_may_set_cap set, it can set these caps as before.

commit 7d26b112452ae5c608906b51cf17c3dae0eb164d
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Nov 28 16:15:53 2019 +0100

    Support all kernel hash functions for password storage.
    Change version to 1.5.4 for new functionality.
    The code tries to stay backwards compatible while adding potentially better
    security for passwords. As long as passwords are hashed with sha1, older RSBAC
    versions can still use them.

commit 6456f7e4a4c29e7a2ceb21ce70cfdf22d0f47d6c
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Nov 27 14:59:20 2019 +0100

    Compile fix for arm: do not define __NR_rsbac explicitely.

commit 5f87d27a77fd3c3b960bd7614353e06d323cf76b
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Nov 26 14:18:57 2019 +0100

    Compile fixes for 5.4.

commit f4a96cc1efa5912e4a15a6b0014a5d7833d33df3
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Nov 18 09:53:54 2019 +0100

    When switching modules, only log, if value changes.

commit 61ca416bbc1f0b4f5ffecde8157b62918b64a507
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Oct 23 12:30:03 2019 +0200

    Add udf_do_check value "remoteonly" to only check, if process has remote_ip set.
    This lets checks only happen, if the accessing process or one of its parents
    has accepted an INET network connection, i.e., acts as an IPv4 network service.

commit 9a4821592d42b777d33a384b04aded4677415f8c
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Sep 24 12:57:26 2019 +0200

    namei.c: do_last(): explicitely check with S_ISREG() before assuming T_FILE.

commit 2b87e19c2de085b41e931b54dcf0399357b13de4
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jun 27 15:04:05 2019 +0200

    Use hash_64 for inode number, uid and gid hashing.

commit ca07612fc63fde8a8c21aa54693b1cc0b52831b9
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jun 27 13:16:16 2019 +0200

    rsbac_um_add_gm(): fix log message with unknown uid.

commit 14ad570f58e4c502106c9da16a3ed0f5b0f4d0f1
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jun 27 12:16:44 2019 +0200

    RSBAC BUG 0000167: rsbac.dat is visible by root user
    aci_data_structures: set device_p->rsbac_dir_inode when looking up rsbac.dat dir.
    This used to be done in lookup_aci_path_dentry() up to kernel 4.14,
    but was missing in the new rsbac_aci_path_open() in 4.19.

commit 017e5d10501c2e17ed7a3260cc06810f483136f1
Author: Amon Ott <ao@rsbac.org>
Date:   Sun Mar 31 08:35:54 2019 +0200

    gen_lists: add extra statistic counters for failed rcu item alloc.

commit 80b0a7b4c8c56d95310042aa672593c4c4130479
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Feb 4 09:55:55 2019 +0100

    gen_lists: add extra synchronize_rcu() before destroying slabs.
    In some cases, there seem to be remaining items in FD cache lists at umount.
    The extra sync allows RCU to remove them in time.
    aci_data_structures: set FD cache handle to NULL before destroying list.

commit 6eb6f01d2d696e13084a512194b355c79e21abae
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 28 13:53:50 2019 +0100

    RSBAC BUG 0000113: CHANGE_DAC_EFF_OWNER and CHANGE_DAC_FS_OWNER doesn't herit from auth_may_setuid 3
    auth: with EFF and FS owner and group, translate RSBAC_UM_VIRTUAL_KEEP and
    RSBAC_UM_VIRTUAL_ALL to current virtual set to correctly match uid or gid.

commit ad4e2c8466d1875cbff23b7d2665334432887e09
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jan 24 11:10:03 2019 +0100

    RSBAC: also avoid access control for writing of RSBAC files at umount.
    rsbac_umount() calls rsbac_write from non-rsbacd context.

commit 2b65166463b8fff312280beefa791560d4b602c6
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jan 23 09:35:16 2019 +0100

    Avoid RSBAC access control for reading of RSBAC files at mount.

commit bbd7032d1504145694f1fbdc0d05533932b3b6a8
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 21 15:53:09 2019 +0100

    BUG 0000163: Kernel parameter does not work: rsbac_switch_off_rc
    Fix #if defined lines and include required header.

commit 17a5f9d32aa296c7ed0fad17817ac98460a656fc
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Jan 8 11:39:01 2019 +0100

    RSBAC: review: remove extra put_pid() in proc, check get_pid result.

commit fcc04a535ce3e3d8112174eac7b206a69aae906a
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 7 12:36:15 2019 +0100

    RSBAC: vfs_kern_mount(): call rsbac_mount() before adding mount to list of mounts
    This avoids access to filesystem objects before RSBAC attributes are set.

commit 8df3879903a7de3da42fec8b0134ccf482681bca
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 7 11:42:56 2019 +0100

    RSBAC: aci: first register per-device FD lists, then per-device FD cache lists
    The cache gets its first entries right after cache registration,
    but the correct attributes must be read first.

commit 872a00b13735e34c9b5b5581ea071e2e31e379a0
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 7 10:37:12 2019 +0100

    RSBAC: remove rsbac_dir_dentry_p from device list entry.

commit 80cd4e331c9cc8b895cc52ea979eb2a97ce4c32d
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Jan 7 10:04:04 2019 +0100

    RSBAC: always check return value of get_task_pid().

commit 1bba6db3ad58e3240b400da2f3da0f028925f9a0
Author: Amon Ott <ao@rsbac.org>
Date:   Fri Jan 4 09:03:05 2019 +0100

    RSBAC: remove rsbac_lookup_one_len()

commit 8a4c2c28cef72b46c05c81ae9ca5a76703a7a09d
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Jan 3 12:43:12 2019 +0100

    RSBAC: make sys_rsbac_write() wake up rsbacd, not write lists directly.

commit 96363e89a5d57758bbf4f8b2353953ca93edeab6
Author: Amon Ott <ao@rsbac.org>
Date:   Wed Jan 2 16:18:56 2019 +0100

    RSBAC: use official functions to open and close files.

commit b5e37ce511762070b9545d0055430a74f74ac4bb
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Dec 27 14:22:59 2018 +0100

    In proc_pid_readdir(), check for valid pid before calling RSBAC.

commit facaab6c89971d29757f1dacee24148c42841cd6
Author: Amon Ott <ao@rsbac.org>
Date:   Thu Dec 13 09:47:27 2018 +0100

    Fix compile error with CONFIG_RSBAC_SECDEL and XFS.

commit dd4f0f1757f87d522c782fd93131623578679bae
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Dec 3 10:09:01 2018 +0100

    Fix merge error in fs/proc/kcore.c

commit fb554769c66c4c0dcf3c2c68344ee4db0847173d
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Dec 3 09:06:10 2018 +0100

    Fix compile warning with missing const in network_types.h.

commit 7e65a51dd1ff5a78721aff5dc467e6bef29d2781
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Nov 19 10:43:44 2018 +0100

    Update rsbac_lookup_one_len() and rename code in rsbac_write_open() for 4.19.

commit 46c02c401651c2ca4bbd9865c1904f8a1712283d
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Nov 13 11:44:08 2018 +0100

    Remove extra CREATE notification from atomic_open().

commit 531bde22c1893f07b672ebfa722761513b700362
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Nov 13 11:30:34 2018 +0100

    Add missing CREATE notifications to atomic_open().

commit 72e8ff85e0cd8a94b2dbf78e43e8da5ba9b70da2
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Oct 30 10:22:20 2018 +0100

    Update MAINTAINERS entry.

commit 2f7c1b0997c1fa452f701d21194bc312ae4cd371
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Oct 30 09:55:36 2018 +0100

    Add SCD target bpf and use it for sys_bpf.
    BPF is not only for firewalling, so make it separate.

commit d8fc1eb322433acf450d070cf5db49be25527ba0
Author: Amon Ott <ao@rsbac.org>
Date:   Tue Oct 30 09:16:58 2018 +0100

    Cleanup whitespace for 4.19.

commit b31cd76ec1544dea574d8ef8dbbe313a9723d5cc
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Oct 29 15:16:50 2018 +0100

    Compile fixes for 4.19.

commit 905948dd1b8dc22f5947df552989ab0e0449dcf7
Author: Amon Ott <ao@rsbac.org>
Date:   Mon Oct 29 11:40:12 2018 +0100

    Port RSBAC from 4.14 git commit d9891837defab3a39d42e046e2d11c2b7854dc51
        Change version to 1.5.3 for IPv6 support.